### PR TITLE
Adding args and env vars for api_key/app_key and title

### PR DESCRIPTION
**Pull request by srhopkins**
Excellent script, thank you. I thought it would be nice to have args for the keys to keep it out of the code and provide flexibility for multi account support.

### CODE REVIEW

**Comment by ckelner** [comment]
@srhopkins would you mind resolving conflicts with master and then we can merge?

**Comment by srhopkins** [comment]
Ran a couple of tests using flags and also using env vars with success. The new delete old dashboard functionality could be added to the parameters; let me know if there would be interest in me adding that and I'll submit another pull later for it.

I also ignored most of the pep8 deviations to avoid cluttering the diffs in the merge. Let me know if you have questions or need anything further.

**Comment by ckelner** [comment]
:+1:

**Comment by ckelner** [comment]
Thanks @srhopkins looks great.

**Pull request merged**
